# Use root/example as user/password credentials
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  net-project:
    name: net-project
    driver: bridge

services:
  proj-injection:
    build:
      context: .
      dockerfile: config-injection/Dockerfile
      target: dev_project
    env_file:
      - config-injection/.env
    image: proj-injection-dev:latest
    hostname: proj-injection
    container_name: proj-injection
    restart: unless-stopped
    networks:
      - net-project
    expose:
      - ${DEFAULT_PYTHON_DJANGO_PORT}
    ports:
      - ${DEFAULT_PYTHON_DJANGO_HOST_PORT}:${DEFAULT_PYTHON_DJANGO_PORT}
    stdin_open: true #docker run -i
    tty: true #docker run -t
    environment:
      - TZ=${DEFAULT_TIMEZONE}
    volumes:
      - proj-injection-volume:/project:rw
    logging: *logging
  proj-postgres:
    # image: docker.io/bitnami/postgresql-repmgr:latest
    image: docker.io/bitnami/postgresql:latest
    restart: unless-stopped
    container_name: proj-postgres
    hostname: proj-postgres
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PROJECT_HOST_PORT}:${POSTGRES_PORT}
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      - POSTGRESQL_POSTGRES_PASSWORD=${RDBMS_ROOT_PASSWORD}
      - POSTGRESQL_USERNAME=${DEFAULT_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_MAX_CONNECTIONS=500
      - POSTGRESQL_USERNAME_CONNECTION_LIMIT=200
      - POSTGRESQL_POSTGRES_CONNECTION_LIMIT=200
    volumes:
      - proj-postgres-volume:/bitnami/postgresql
    networks:
      - net-project
    logging: *logging
  proj-redis:
    image: docker.io/bitnami/redis:latest
    restart: unless-stopped
    container_name: proj-redis
    hostname: proj-redis
    ports:
      - "${REDIS_PROJECT_HOST_PORT}:${REDIS_PORT}"
    expose:
      - ${REDIS_PORT}
    networks:
      - net-project
    logging: *logging
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      # - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - proj-redis-data-volume:/bitnami/redis/data

volumes:
  proj-injection-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_PROJECT_DIR}/proj-injection
  proj-redis-data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_PROJECT_DIR}/databases/redis
  proj-postgres-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_PROJECT_DIR}/databases/postgres
