# Generated by Django 5.1.2 on 2024-10-11 13:43

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_initial_data(apps, schema_editor):
    """superuser와 테스트할 사용자를 생성함."""
    Accounts = apps.get_model("accounts", "Accounts")
    Accounts.objects.create(
        username="admin",
        password=make_password("1qaz2wsx2"),
        first_name="admin",
        last_name="jo",
        email="example@example.com",
        is_superuser=True,
        is_staff=True,
        is_active=True,
    )
    Accounts.objects.create(
        username="string",
        password=make_password("string"),
        first_name="test",
        last_name="test",
        email="abcd@abcd.com",
        is_superuser=False,
        is_staff=False,
        is_active=True,
    )


class Migration(migrations.Migration):
    """app(accounts) Database Migration."""

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.RunPython(create_initial_data),
    ]
