# Generated by Django 5.1.2 on 2024-10-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionMoldingMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=256)),
                ('status', models.SmallIntegerField(choices=[(0, 'POWEROFF'), (1, 'POWERON'), (2, 'RUNNING'), (3, 'PAUSE'), (4, 'FAILURE'), (5, 'ERROR')])),
                ('owner_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'injection_molding_machines',
            },
        ),
    ]
