# Generated by Django 5.1.2 on 2024-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machineshistory_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionmoldingmachines',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'POWEROFF'), (1, 'READY'), (2, 'PAUSE'), (3, 'RUNNING'), (4, 'PENDING'), (5, 'ERROR')], default=1),
        ),
        migrations.AlterField(
            model_name='machineshistory',
            name='result',
            field=models.SmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED'), (3, 'PENDING')]),
        ),
    ]
